### ISSUE TITLE
"transfer-encoding: chunked" の write 実装

### ISSUE THREAD

**Issue by motxx** [yuki-kimoto/SPVM#114]
`/chunk/echo` に `chunked` のデータを POST し、同じ文字列のレスポンスを受け取れるか確認します。

**Comment by yuki-kimoto** [comment]
認識合わせですが、

アップロード方向とダウンロード方向の両方で、

chankedを確かめるという認識であっていますか?

**Comment by yuki-kimoto** [comment]
バグ報告

クライアントの試験がストップすることがあります。

無限ループしているか、ブロッキングしているかは、ちょっとわかりませんが、

とりあえず報告。

**Comment by motxx** [comment]
> アップロード方向とダウンロード方向の両方で、

アップロードの方向の chunked がまだなので、実施する予定です。

バグの件ですがすみません、報告ありがとうございます。
無限ループ(or ブロッキング)しているケースと、
途中で例外を吐いて停止するケースがあるので、少し整理してからこの issue より先に別 issue で修正します。

**Comment by yuki-kimoto** [comment]
試験コードを見て、ちょっと勘違いしているかなと思ったのは、

_dump_responseで出力するのは、途中経過の段階のコードを確認するためで、

レスポンスが返ってきた今の段階では、試験コードを書く必要があります。

unless ($status == 200) {
  return 0;
}
unless ($response->{content} eq "foo") {
  return 0;
}

**Comment by yuki-kimoto** [comment]
こちらも、SPVM::HTTPの外出し化を行うので、いったんクローズしますね。
