### ISSUE TITLE
直IPでソケット接続すると書き込み時に例外が発生する

### ISSUE THREAD

**Issue by motxx** [yuki-kimoto/SPVM#116]
本番サーバ接続で `http://testserver.spvm.info` へのGETリクエストは正しく動く。
開発サーバ接続で `http://153.121.46.88:3010` へのGETリクエスト時に例外が発生する。

**Comment by yuki-kimoto** [comment]
こちら調査開始します

**Comment by yuki-kimoto** [comment]
調べたところ、IPアドレスを指定した場合は

接続するロジックを実行していなかったというバグでした。

masterで修正しました。
