### ISSUE TITLE
JSONのリファクタリング

### ISSUE THREAD

**Issue by yuki-kimoto** [yuki-kimoto/SPVM#129]
<b>解析するJSONテキストの長さ</b>

SPVMの場合は、文字列が長さを持っていますので、$endを引数で渡さなくてもいけそうです。

<b>文字列の動的リスト</b>

現在SPVM::ObjectListですが、SPVM::StringBufferでいけそうな気がします。

https://github.com/yuki-kimoto/SPVM/blob/master/lib/SPVM/JSON.spvm#L560
https://github.com/yuki-kimoto/SPVM/blob/master/lib/SPVM/JSON.spvm#L68

その他もObjectListを使わないでよさそうな場所があれば、修正できそうです。

<b>SPVM::StringBufferへ、push_range, push_charを追加</b>

```
sub push_range($self : self, $str : string, $offset : int, $len : length);

sub push_char($self : self, $char : byte);
```

<b>decode関数の実装</b>

decode関数の中身を_decode_recursiveを呼び出すだけにできそうです。

```
return $self->_decode_recursive(...);
```

<b>_skip_spacesだけにする</b>

_skip_spaces_at_not_endを削る。

<b>引数渡しの$sと$iに長い名前をつける</b>

引数渡しの$sと$iに長い名前をつける

<b>ERRは通常のメソッドなので小文字でOK</b>

ERRは通常のメソッドなので小文字でOK

<b>プライベートなメソッドにprivateを追加</b>

プライベートなメソッドにprivateを追加。

<b>すべてのメソッドにprecompileを追加</b>

JSONは、パフォーマンスが求められるモジュールなので、precompileします。

Makefile.PLの修正も合わせて必要になります。

<b>試験のリファクタリング</b>

処理ごとに試験を分割できそうです。

encode_null
encode_string
decode_null
decode_string

のように、値と、decodeとencodeで分割。

<b>$grok_negを普通のサブルーチンへ</b>

$grok_negを普通のサブルーチンへ。

理由: precompileを指定したときに、キャッシュが効かないため。

**Comment by motxx** [comment]
ご指摘をPR に反映させました。一部、相談があります。

> decode関数の中身を_decode_recursiveを呼び出すだけにできそうです。

`_decode_recursive` の呼出前の処理で `decode` の入力が `空文字列 or 空白類のみ` を何故か許容していましたが、これは不適切だと思い削除しました。ありがとうございます。

<details>
<summary>RFC8259の文法定義の引用</summary>

https://www.rfc-editor.org/rfc/rfc8259.txt

```
JSON-text = ws value ws

...

value = false / null / true / object / array / number / string
```
</details>


`_decode_recursive` の呼出後ですが、余った文字列があるときに例外を吐いています。この処理の必要性はどの程度でしょうか？

https://github.com/yuki-kimoto/SPVM/pull/130/commits/10f01c57dedab8b6d650de47f5da9b8f386d0633

`JSON::XS` の例

```
$ perl -MJSON::XS -e '$json = JSON::XS->new; $json->decode("{ \"key\": 123 } [1,2]")'
garbage after JSON object, at character offset 15 (before "[1,2]") at -e line 1.
```

> 試験のリファクタリング
> decodeとencodeで分割。

データ構造を再帰的に読んで比較する `Test::More::is_deeply` のような関数が必要になりますが、テストコード内に実装するか、テスト用のモジュールを作るのはどちらが良いでしょうか。

**Comment by yuki-kimoto** [comment]
必要ないんじゃないかなぁ。空白だけ残った場合は、OKだと思います。

**Comment by motxx** [comment]
ありがとうございます。対応しました。

**Comment by yuki-kimoto** [comment]
>SPVM::JSON->decode で行末に空白類以外のゴミがあった場合に無視する

あれ、空白以外は、エラーにしないといけないですよ。

**Comment by yuki-kimoto** [comment]
僕の勘違いで、やっぱり、必要ですね。

再帰下降パーサーによる解析が終わった時点で、空白以外の文字列が、末尾に、残っていた場合は、エラーにしないといけないですね。

**Comment by yuki-kimoto** [comment]
>他の ObjectList を使っている箇所は JSON の配列の要素の型に制約がないので難しそうです。

了解です。

**Comment by yuki-kimoto** [comment]
レビューの続きです。

<b>JSONの数値はすべて、SPVMのSPVM::Doubleへ変換</b>

小数点の有無で、整数か浮動小数点化を判定していましたが、JSONの数値はすべてSPVMのSPVM::Doubleへの変換でお願いします。

<b>_custom_dieの名前を改善</b>

_custom_dieの名前を改善できそうです。

「JSON解析のエラーメッセージを位置を含めて表示する」

という内容のようですので、短くて想像しやすいサブルーチン名を。

<b>_atofと_atof_scan1の名前改善</b>

_atofと_atof_scan1をもう少し名前改善ができそうです。


<b>_grok_negと_grok_non_negの名前改善</b>

grokという単語よりもう少し、わかりやすい名前の改善。

**Comment by motxx** [comment]
> JSONの数値はすべて、SPVMのSPVM::Doubleへ変換

こちらの対応でコード量が大きく減りました。`_grok_neg`, `_grok_non_neg` も不要になったので削除しました。

> _custom_dieの名前を改善

`decode` 時のみ効果がある関数なので `_decode_error` を使ってみましたが、
`_decode_*` という正常系の関数があるので改善したいです。

> _atofと_atof_scan1の名前改善

コードを整理して `_atof` にあたる関数を削除しました。命名は一旦 `_decode_num_recursive` としましたが、こちらも検討中です。

**Comment by yuki-kimoto** [comment]
レビュー続きです。

<b>decode関数内でコメント</b>

557行目から561行目までの処理に対して、短いコメントをお願いします。
https://github.com/yuki-kimoto/SPVM/blob/json-refactor-again/lib/SPVM/JSON.spvm#L557

**Comment by yuki-kimoto** [comment]
レビューの続きです、先に、_decode_numを少しリファクタリングします。

**Comment by yuki-kimoto** [comment]
完成しましたので、クローズしますね。
