### ISSUE TITLE
GitHub Actions で CI を導入する

### ISSUE THREAD

**Issue by motxx** [yuki-kimoto/SPVM#156]
GitHub Actions で CI を導入します。
実行環境は Linux とします。また、未使用の appveyor.yml を削除します。

**Comment by yuki-kimoto** [comment]
macでも試験を追加することは、可能ですか。

moti君のmacでは試験が通って、伊藤さんのmacでは、試験が通らないということが起こっていて、

macの試験が欲しいというのがあります。

**Comment by motxx** [comment]
こちらで作成しています :bow:
https://github.com/yuki-kimoto/SPVM/actions
