### ISSUE TITLE
SPVM::List

### ISSUE THREAD

**Issue by motxx** [yuki-kimoto/SPVM#16]
Discussions about `SPVM::List` specifications.

## Just idea of basic interface
```perl
package SPVM::List {
    sub new : SPVM::List () {
    }
    
    sub new_with_capacity : SPVM::List ($capacity : int) {
    }

    sub length : int ($self : self) {
    }
    
    sub push : void ($self : self, $value : object) {
    }
    
    sub pop : object ($self : self) {
    }

    sub unshift : void ($self : self, $value : object) {
    }
    
    sub shift : object ($self : self) {
    }
    
    sub set : void ($self : self, $index : int, $value : object) {
    }
    
    sub get : object ($self : self, $index : int) {
    }

    sub splice : ($self : self, $offset : int, $length : int) {
    }
}
```

- The computational complexity
  - `push`, `pop`, `unshift`, `shift`, `get`, `set` - O(1)
  - `splice` - O(n)

## TBD
- constant chunk:
  - Allocating capacity when not enough takes `O(n)`.
  - Introducing constant size `chunk` will take `O(1)`.
  - Reference: http://cpp-tip-of-the-day.blogspot.com/2013/11/how-is-stddeque-implemented.html
- allow autovivification

**Comment by yuki-kimoto** [comment]
Thank you.

OK. very good!

I realize some points.

1. get method need to return object instead of void.
2. splice method is needed.
3. new method need () for empty arguments.

**Comment by motxx** [comment]
Thank you. I revised the above interface.

**Comment by yuki-kimoto** [comment]
o(1) is

shift
unshift
pop
push
get
set

o(n) is

splice

**Comment by yuki-kimoto** [comment]
constant chunk:

I don't know yet internally implementation of Perl array completly.

I try to read Perl itself at first.

At first, try to implement SPVM::List by only use "capacity"?

**Comment by motxx** [comment]
Ok. I'll try to implement it by using "capacity".
