### ISSUE TITLE
Is it possible to directly call a SPVM subroutine in C++ code

### ISSUE THREAD

**Issue by maxc01** [yuki-kimoto/SPVM#174]
To call a SPVM subroutine, as far as I am aware, I can use `get_sub_id` then `call_sub`. However, this mechanism has a limitation when a third-party C++ library needs a function parameter. For example, in [LBFGS++ ](https://github.com/yixuan/LBFGSpp/), a function parameter is directly passed to `minimize`.  
```
solver.minimize(obj_func, x_init, res);
```
 Of course, I can write the objective function to be optimized in C++ code, but doing so will lose some convenience of SPVM. My question is, is there a workaround on that?

**Comment by yuki-kimoto** [comment]
I still don't understand the question correctly, but I get the question of how to pass a C++ type.

The method prepared by SPVM is to use the pointer_t type.

Search by pointer_t
https://yuki-kimoto.github.io/spvmdoc-public/language.html#language-type-pointer

This type express any C/C++ pointer type.

**Comment by maxc01** [comment]
Hi, it seems there is a small issue in your documentation, `new_pointer` expects  a `int32_t type_id` instead of a string, and the following is a correct version:
```
  int32_t type_id = env->get_basic_type_id(env, "Foo::Bar");
  if (type_id < 0) {
    std::cout << "Error, cannot find type_id" << std::endl;
    // SPVM_DIE ("Can't find type id", "Foo/Bar.cpp", __LINE__);
    return SPVM_EXCEPTION;
  }
  void *param_obj = env->new_pointer(env, type_id, param_ptr);
```
Now back to my original question. In LBFGSpp, the signature of `minimize` is:
```
int minimize(Foo& f, Vector& x, Scalar& fx)
```
where `f` is a function object with signature `double (Vector&, Vector&)`. To make a SPVM binding useful and convenient, it is better to write `f`, the function we want to optimize, using SPVM instead of C++. In this case, my question is: how to pass a subroutine written in SPVM to function `minimize`? For example, suppose I have the following subroutine, how can I pass it to `minimize`, which requires a callable parameter. 
```
package Rosenbrock {
  has n: ro int;
  sub new: Rosenbrock ($n: int) {
    my $self=new Rosenbrock;
    $self->{n}=$n;
    return $self;
  }
  sub : double ($self: self, $x : double[], $grad: double[]) {
    my $fx=0;
    # ...
    return $fx;
}
}
```

**Comment by yuki-kimoto** [comment]
I'm thinking now. please wait for a while.

**Comment by yuki-kimoto** [comment]
Thank you. I will fix document.

**Comment by yuki-kimoto** [comment]
If your question is how to pass callbacks in SPVM, here's the answer.

use Callback Type(callback_t) and Callback object.

https://yuki-kimoto.github.io/spvmdoc-public/language.html#language-type-callback

https://yuki-kimoto.github.io/spvmdoc-public/language.html#language-sub-new-callback-object

**Comment by maxc01** [comment]
Hi, after some study, I guess it is impossible to do what I want to do just by calling a third-party cpp library and I need to directly write SPVM code to finish this task. So I will close this issue.
