### ISSUE TITLE
[DRAFT] interface of SPVM::JSON

### ISSUE THREAD

**Issue by motxx** [yuki-kimoto/SPVM#25]
## 現状

取り敢えず感覚で decode を実装し、現在 encode の実装＋テスト作成＋decodeの修正をはじめているところです (RFC との対応が出来ているかなど、細かい考慮も後回しにしました)

現状：https://github.com/yuki-kimoto/SPVM/compare/ab67f484cd3f66445de8ca12a63e13596460af17...json

( https://metacpan.org/pod/JSON::PP は見ておりますが、incremental parser 周辺のインターフェースが十分に理解できていません...... )

## インターフェースの提案

`encode`, `decode` は必須かと思います。

他に、折角 `SPVM::JSON` というオブジェクトを作るので、メソッドチェーンで再帰的にデータを扱えると嬉しいと思いましたがどうでしょうか。
`JSON::PP` ではどうなっているかは、よく理解できていないです。

インターフェースの案、利用例は以下のとおりです。

参考にした考え方: https://github.com/kazuho/picojson

インターフェースの案
```perl
package SPVM::JSON {
  sub encode : string ($self : self);
  sub decode : SPVM::JSON ($json_text : string);
  sub pretty : string ($self : self);
}

package SPVM::JSONHash {
  sub value : SPVM::Hash ($self : self);
  sub get : SPVM::JSONValue ($self : self, $key : string);
}

package SPVM::JSONList {
  sub value : SPVM::List ($self : self);
  sub get : SPVM::JSONValue ($self : self, $index : int);
}

package SPVM::JSONValue {
  sub as_hash : SPVM::JSONHash ($self : self);
  sub as_list : SPVM::JSONList ($self : self);
  sub type : string ($self : self); # 値の型を返す ("Hash", "List", "Int", "Long", "Double")
  sub is_hash : int ($self : self);
  sub is_list : int ($self : self);
}
```

利用例
```perl
my $json = SPVM::JSON->decode("{\"key1\":{\"key2\":[1,2,3]}}")
my $value : int = $json->as_hash->get("key1")->as_hash->get("key2")->as_list->get(2)->as_int;
my $j_value : SPVM::JSONValue = $json->as_hash->get("key1");
my $j_hash : SPVM::JSONHash = $json->as_hash;
my $j_list : SPVM::JSONList = $json->get("key1")->as_hash->get("key2")->as_list;
my $hash : SPVM::Hash = $json->as_hash->value;
my $list : SPVM::List = $json->get("key1")->as_hash->get("key2")->as_list->value;
```

**Comment by yuki-kimoto** [comment]
> encode, decode は必須かと思います。

はい、これは必要です。

**Comment by motxx** [comment]
`my $string = $json->encode($object);` の `$object` には `SPVM::Hash` や `SPVM::LIst` などが入れば良いですよね？`$json->{is_pretty_print} = 1` のときに、`$string` の出力値がいい感じになる形ですよね。

`SPVM::JSON` の内部にはJSONのパース済みのデータは持たずに、エンコード/デコードのための設定値だけ持つようにすればよいということですね。

自分の勘違いがあって、`JSON::PP` のインターフェースを十分に理解してなかったようです。はじめインスタンスの内部にパース済みのデータを持つべきかと思い、`decode` でパースして `$json->as_hash->get("key1")->...` でアクセスするものかと思いましたが、間違っておりました。

> 必要なモジュールはSPVM::JSONモジュールだけで、大丈夫な気はします。

理解いたしました 🙇

**Comment by yuki-kimoto** [comment]
はい。

内部的に持つわけではなく、encode、decodeで、JSONとSPVMデータ構造を変換します。

**Comment by motxx** [comment]
ありがとうございます。解決したのでクローズいたします。
