### ISSUE TITLE
Cannot convert byte array -> string -> object -> string

### ISSUE THREAD

**Issue by motxx** [yuki-kimoto/SPVM#26]
`SPVM::JSON` で、 `string` 型の値の decode, encode をテストを作成しており、次のような convert を内部で行っております。

`byte[]` -> `string` -> `object` -> `string`

この際にAssertionや例外が発生したため、以下に再現するコードを記載いたします：
```perl
    my $b = ['a','b'];
    my $s = (string)$b;
    print("s: $s\n");
    # print("s - len: " . length($s) . "\n"); # Assertion failed: (0), function SPVM_OP_get_target_op_var, file lib/SPVM/Builder/src/spvm_op.c, line 1076.
    my $o = (object)$s;
    # my $t = (string)$o; # Can't convert imcompatible object type. # ミスマッチした型: SPVM_BASIC_TYPE_C_ID_BYTE, SPVM_BASIC_TYPE_C_ID_STRING
```

**Comment by yuki-kimoto** [comment]
Assertionが出ないように修正します。

**Comment by yuki-kimoto** [comment]
型変換で、元に戻らないのは、やっぱり、実装がおかしいね。

現状の実装は、byte[] から stringへの変換は単なるキャストなんだけど、

このバグを修正するには、実体をコピーして新しくオブジェクトを作らないといけなそうだね。

**Comment by yuki-kimoto** [comment]
string と byte[]の変換は、両方の方向でコピーする実装を修正する方向で行きます。

**Comment by yuki-kimoto** [comment]
昨日一晩考えました。

コピーするとコストになるのとC言語との相性を考えて、今の実装にしていたことを忘れていました。

string型は、コンパイル時型にして、実行時にはstring型はbyte[]型として扱われるものとして実装してみます。

**Comment by yuki-kimoto** [comment]
こちら最新のmasterで修正しました。
