### ISSUE TITLE
文字列をC言語型の仕様と合わせる変更について

### ISSUE THREAD

**Issue by yuki-kimoto** [yuki-kimoto/SPVM#28]
stringとbyte[]の関係について、考えているのですが、

moti君の問題提起で、

現状の実装だと問題があることがわかりました。

stringからbyte[]への変更を不可にしておいたのに、

stringからobjectに変換した後に、byte[]への変換が可能なので、

文字列は結局、どんな場合においても、ミュータブルになるということがわかりました。

ですので、以下の変更を加えます。

1. stringは、C言語における「const char*」を意味する
2. byte[]は、C言語における「char*」を意味する
2. 実行時には「const」な情報は完全になくなり「byte[]」と「string」はまったく同じになります。
3. stringからbyte[]への型変換、byte[]からstringへの型変換は可能で、キャストを意味します。コピーは発生しません。
4. byte[]型の変数をstring型の変数に代入できます。
5. string型の変数をbyte[]の変数に代入するには、明示的な型変換を記述しない限り、コンパイルエラーとなります。
6. コピーをする場合は常に「copy_string」あるいは「copy_byte_array」を使用します。

**Comment by yuki-kimoto** [comment]
型の仕様と変換規則をまだ文書にしていないので、仕様化していきますね。

**Comment by yuki-kimoto** [comment]
感覚的には、以下の感じです。

実体化されたオブジェクトは、内部的に、「基本型」と「次元」の情報を持っています。

基本型と次元が、完全に一致した場合に、objectから実体型への変換が成功します。

オートボクシングが実装されているので、(int)$objectのように書けるように見えますが

これは実際には

```
((SPVM::Int)$object)->val
```

と同じ意味になります。

**Comment by motxx** [comment]
なるほど。オブジェクトの意味を理解しました。

**Comment by yuki-kimoto** [comment]
これに伴い、keys関数をコピーを使うように修正しました。

```
  sub keys : string[] ($self : self) {
    my $retval = new string[$self->{count}];
    # iterate entries
    my $count = 0;
    for (my $i = 0; $i < $self->{bucket_count}; ++$i) {
      my $ref = $self->{entries}->[$i];
      while ($ref) {
        $retval->[$count++] = copy_string($self->{entries}->[$i]->key);
        $ref = $ref->next_entry;
      }
    }
    return $retval;
  }
```

**Comment by yuki-kimoto** [comment]
それと、

型名を返すtype_name関数を追加しました。

```
my $type_name = type_name($object);
```

isaで、数値型の型チェックができるようになりました。

```
my $num : byte;
if ($num isa byte) {
  
}
```

デバッグにご利用ください。
