### ISSUE TITLE
SPVM::JSON

### ISSUE THREAD

**Issue by yuki-kimoto** [yuki-kimoto/SPVM#34]
ルートがプリミティブなのを valid な JSON とすべきか否か (RFC8259 などを見れば分かる？)

encode のフォーマットについて、オーバーヘッドを考慮して pretty の property でのみ対応するのもありか？

relaxed のオーバーヘッドは？対応すべきか？

テストで object の内容比較をしているが、Test::More のような utility のモジュールに切り出してもいいかも知れない。

**Comment by yuki-kimoto** [comment]
doubleの試験が、僕の環境では、ひとつ落ちるみたい。

```
t/precompile/lib-SPVM-JSON.t ........... 1/? lhs: 1.23456e-18 rhs: 1.23e-18

#   Failed test at t/precompile/lib-SPVM-JSON.t line 21.
# Looks like you failed 1 test of 12.
```

原因は、まだわからない。

**Comment by yuki-kimoto** [comment]
>encode のフォーマットについて、オーバーヘッドを考慮して pretty の property でのみ対応するのもありか？

>relaxed のオーバーヘッドは？対応すべきか？

何か提案はありますか?

**Comment by yuki-kimoto** [comment]
>テストで object の内容比較をしているが、Test::More のような utility のモジュールに切り出してもいいかも知れない。

標準モジュールや標準関数は、作成して大丈夫ですよ。

モジュール名とサブルーチン名の整理は後で、やりますのです。

**Comment by yuki-kimoto** [comment]
ルートがプリミティブなのを valid な JSON とすべきか否か (RFC8259 などを見れば分かる？)

最新のJSON仕様では、validとなっていたはず。

「最新のJSON仕様、オブジェクトではなくてもOK」みたいなので、検索すれば出てくると思います。

**Comment by motxx** [comment]
> `Double` の一般的な encode 方式
指数表記にする基準, デフォルトの実装

- 基本的に各言語・ライブラリ依存
- JSON::XSに合わせるなら現状で問題ない
- 固定小数点表記のポリシーを作っても良い

## JSON::XS

`SPVM::JSON` の現状の浮動小数点の扱いは `JSON::XS` にほぼ同じ

### encode
- `sprintf(..., "%g", ...)` (=`Gconvert`マクロ) で実行される。
=> SPVM の `string` にキャストする挙動と同じ

### decode
- `Perl_pow` の精度に依存
- 整数部と小数部で別々に計算する
  - それぞれ数字をパースして `Perl_pow` で 10 のべき乗を計算した結果を足し込む。
  - 別々に計算する精度上の理由はないと思う。

## JavaScript

- JavaScript は数値を IEEE754 の 64ビット倍精度 として保持しており、 2^53 - 1 未満の数値まで扱える。JSON の精度もこの規格に従う。
- 数値は `toFixed` を使って固定小数点表記でフォーマットできる

## Java

- 17桁までで切り捨てか？
- BigDecimalをサポートしており、桁落ちなくパースできる。

**Comment by yuki-kimoto** [comment]
encodeはJSON::XSは%gなんですね。

**Comment by yuki-kimoto** [comment]
さらに気が付いてしまった点

JSONがinf,nanをサポートしていないので、他の何かにマッピングしないといけないということに気がつきました。

inf,-inf,nanの変換

https://metacpan.org/pod/Cpanel::JSON::XS#$infnan_mode-=-$json-%3Eget_stringify_infnan

**Comment by yuki-kimoto** [comment]
整数値のdecodeは、intで、オプションで、longやビックインテジャーという感じかな。

.かeかEが入っていた場合は、doubleで、オプションで、ビッグデシマルという感じかな。

**Comment by yuki-kimoto** [comment]
いったんクローズします。
