### ISSUE TITLE
Any multithreading support?

### ISSUE THREAD

**Issue by please-fill-out-this-field** [yuki-kimoto/SPVM#379]
Let's say I want to run some blocking code in parallel (`fork()` won't work as I need shared memory). Is that possible with SPVM? How do I do that?

Thanks!

**Comment by yuki-kimoto** [comment]
Sorry, Currently multi-threading are not supported . If you try to run with multithreading, the object release operation will cause a segfault because there is no synchronous.

I will work on multithreading after I implemenet the features (reflection) and introduce POSIX mutexes so that the SPVM program will work properly.

**Comment by yuki-kimoto** [comment]
This is moved to Wiki.

https://github.com/yuki-kimoto/SPVM/wiki/FAQ#any-multithreading-support-lets-say-i-want-to-run-some-blocking-code-in-parallel-fork-wont-work-as-i-need-shared-memory-is-that-possible-with-spvm-how-do-i-do-that

**Comment by yuki-kimoto** [comment]
@please-fill-out-this-field

I implemented the following module.

SPVM::Thread

https://metacpan.org/pod/SPVM::Thread

SPVM::Go

https://metacpan.org/pod/SPVM::Go

An example:

```
    my $results = new int[2];
    
    Go->go([$results : int[]] method : void () {
      my $wg = Go::Sync::WaitGroup->new;
      
      $wg->add(2);
      
      my $thread0 = Thread->new([$wg : Go::Sync::WaitGroup, $results : int[]] method : void () {
        Fn->defer([$wg : Go::Sync::WaitGroup] method : void () {
          $wg->done;
        });
        
        Sys->sleep(1);
        
        $results->[0] = 1;
      });
      
      my $thread1 = Thread->new([$wg : Go::Sync::WaitGroup, $results : int[]] method : void () {
        Fn->defer([$wg : Go::Sync::WaitGroup] method : void () {
          $wg->done;
        });
        
        $results->[1] = 2;
      });
      
      $wg->wait;
      
      $thread0->join;
      $thread1->join;
      
    });
    
    Go->gosched;

```

**Comment by please-fill-out-this-field** [comment]
> @please-fill-out-this-field
> 
> I implemented the following module.
> 
> SPVM::Thread
> 
> https://metacpan.org/pod/SPVM::Thread
> 
> SPVM::Go
> 
> https://metacpan.org/pod/SPVM::Go
> 
> An example:
> 
> ```
>     my $results = new int[2];
>     
>     Go->go([$results : int[]] method : void () {
>       my $wg = Go::Sync::WaitGroup->new;
>       
>       $wg->add(2);
>       
>       my $thread0 = Thread->new([$wg : Go::Sync::WaitGroup, $results : int[]] method : void () {
>         Fn->defer([$wg : Go::Sync::WaitGroup] method : void () {
>           $wg->done;
>         });
>         
>         Sys->sleep(1);
>         
>         $results->[0] = 1;
>       });
>       
>       my $thread1 = Thread->new([$wg : Go::Sync::WaitGroup, $results : int[]] method : void () {
>         Fn->defer([$wg : Go::Sync::WaitGroup] method : void () {
>           $wg->done;
>         });
>         
>         $results->[1] = 2;
>       });
>       
>       $wg->wait;
>       
>       $thread0->join;
>       $thread1->join;
>       
>     });
>     
>     Go->gosched;
> ```

Wow that looks cool. Already employed a different solution for my original issue, but it's a great thing that SPVM is being actively developed. Keep up the great work!
