### ISSUE TITLE
HTTPリクエストとレスポンス

### ISSUE THREAD

**Issue by yuki-kimoto** [yuki-kimoto/SPVM#42]
HTTPリクエストとレスポンスについてのissueです。

**Comment by yuki-kimoto** [comment]
箇条書きでよいので、必要と思われるものを列挙しませんか?

**Comment by motxx** [comment]
## Request の解析

- リクエストの文字列を解析して、結果を Request クラスに Hash で渡す
- パース => ハッシュ生成のために request の incremental parser を作成する
  - event-loop で少しずつパースする必要があるので incremental にする
- 参考
  - [cpp-netlib/async_connection.hpp at master · cpp-netlib/cpp-netlib · GitHub](https://github.com/cpp-netlib/cpp-netlib/blob/master/boost/network/protocol/http/server/async_connection.hpp)
  - [cpp-netlib/request_parser.hpp at master · cpp-netlib/cpp-netlib · GitHub](https://github.com/cpp-netlib/cpp-netlib/blob/master/boost/network/protocol/http/server/request_parser.hpp)
  - [cpp-netlib/incremental.hpp at master · cpp-netlib/cpp-netlib · GitHub](https://github.com/cpp-netlib/cpp-netlib/blob/master/boost/network/protocol/http/parser/incremental.hpp)

## Response の生成

- Validation 用途に Incremental Parser が必要か

## SPVM::HTTP::Request

- constructor でパースする
  - Hash => field に落とし込む

## SPVM::HTTP::Response

- builder pattern で実装
- `add_body` などで設定
- `finalize` でイミュータブルになる

## SPVM::URI

- Perl の URI - RFC2396, RFC2732 の URI を OOP で扱うライブラリを参考に
  - [URI-1.76 - Uniform Resource Identifiers (absolute and relative) - metacpan.org](https://metacpan.org/release/URI)

- `URI::Split` はここに実装しても良いのでは？
  - `URI::Split` - URI の join, split を行うライブラリ

### SPVM::URI::Escape

- [URI::Escape - Percent-encode and percent-decode unsafe characters - metacpan.org](https://metacpan.org/pod/URI::Escape)

### SPVM::URI::URL

- [URI::URL - Uniform Resource Locators - metacpan.org](https://metacpan.org/pod/URI::URL)

### SPVM::URI::QueryParam

- [URI::QueryParam - Additional query methods for URIs - metacpan.org](https://metacpan.org/pod/URI::QueryParam)

### 様々なプロトコル

- Perl の URI は継承でいろんなプロトコルに対応してる
- 煩雑にならない範囲で interface_t で抽象化できるか

**Comment by yuki-kimoto** [comment]
>URL以外のプロトコル

コアで提供するのは、httpとhttpsのURL限定でいきませんか?

**Comment by yuki-kimoto** [comment]
レスポンスとリクエストをインクリメンタルで解析するのは、必要ですね。

ソケットは使えないですが、指定したバイト数読み込みの機能は、コアのfreadで実装しているので、で、最終的なものに近い感じになる気がします。

**Comment by yuki-kimoto** [comment]
名前空間は、SPVM::HTTPの下に、すべてそろえませんか?

**Comment by yuki-kimoto** [comment]
リクエストのボディにjsonがあったときに、プログラム側では、Perlのデータ構造として利用できる機能をプラス。

JSONをHTTPレスポンスのボディに書き込める機能をプラス。

**Comment by yuki-kimoto** [comment]
HTTPリクエストは、日付と時刻が含まれていると思うので、もし扱いにくかったら、モジュール化してもよいかな。

**Comment by yuki-kimoto** [comment]
HTTPリクエストは、ボディにファイルを添付することができるから、それを扱えるモジュールも必要かもね。

**Comment by yuki-kimoto** [comment]
今、思いつくのは、これくらいかな。

**Comment by motxx** [comment]
ありがとうございます。頂いた意見を適用して interface を書いてみます。

**Comment by motxx** [comment]
まだ検討事項が多いですが、現状以下のようなイメージです

## SPVM::HTTP::Request

```perl
has content_type : public string;
has content : public string;
has json : public SPVM::JSON;

sub new : SPVM::HTTP::Request ();
sub new_with : SPVM::HTTP::Request ($env : SPVM::Hash);
sub new_with_method : SPVM::HTTP::Request ($method : string, $url : string);
sub parse : SPVM::HTTP::Request ($str : string);
sub as_json : SPVM::JSON ($self : self);
```

### SYNOPSIS

```perl
my $request = SPVM::HTTP::Request->new_with(new_hash([
  method        => "GET",
  url           => "http://www.example.com/",
  header        => SPVM::HTTP::Headers->new,
  content_type  => "text/html",
  content       => "content",
]));
```
```perl
my $request = SPVM::HTTP::Request->parse("GET / HTTP/1.0\r\nHost: ...\r\n\r\n");
```

### METHODS

#### constructors

```perl
my $request = SPVM::HTTP::Request->new;
```

```perl
my $request = SPVM::HTTP::Request->new_with(new_hash([
  method        => "GET",
  url           => "http://www.example.com/",
  header        => SPVM::HTTP::Headers->new,
  content_type  => "text/html",
  content       => "content",
]));
```

```perl
my $request = SPVM::HTTP::Request->new_with_method(GET => "http://www.example.com/");
```

#### as_json

```perl
eval {
  $object = $request->as_json;
};
if ($@) {
  croak "malformed";
}
```

```perl
eval {
  $request->{json} = SPVM:JSON->new->{relaxed} = 0;
  $object = $request->as_json;
};
if ($@) {
  croak "malformed";
}
```

## SPVM::HTTP::Request::Builder

```perl
sub GET : SPVM::HTTP::Request::Builder::_GET ($url : string);
sub HEAD : SPVM::HTTP::Request::Builder::_HEAD ($url : string);
sub POST : SPVM::HTTP::Request::Builder::_POST ($url : string);
sub PUT : SPVM::HTTP::Request::Builder::_PUT ($url : string);
```

### SYNOPSIS

```perl
my $request = SPVM::HTTP::Request::Builder
  ->POST("http::/example.com")
  ->add_json($json)
  ->finalize();
```

### SPVM::HTTP::Request::Builder::_GET

```perl
sub add_query_params : SPVM::HTTP::Request::Builder::_GET ($self : self, $query_params : SPVM::HTTP::URL::QueryParams);
```

### SPVM::HTTP::Request::Builder::_HEAD

- TODO

### SPVM::HTTP::Request::Builder::_PUT

- TODO

### SPVM::HTTP::Request::Builder::_POST

```perl
sub add_json : SPVM::HTTP::Request::Builder::_POST : ($self : self, $json_obj : object);
sub add_html : SPVM::HTTP::Request::Builder::_POST : ($self : self, $html : string);
sub add_plain : SPVM::HTTP::Request::Builder::_POST : ($self : self, $plain : string);
```

## SPVM::HTTP::Response

```perl
has status : public int;
has headers : public SPVM::HTTP::Headers;
has content_type : public string;
has content_length : public int;
has content_encoding : public string;

sub new : SPVM::HTTP::Response ();
sub new_with : SPVM::HTTP::Response ($env : SPVM::Hash);
sub redirect : void ($args : string[]);
```

### SYNOPSIS

```perl
my $res = SPVM::HTTP::Response->new_with(new_hash[
  status => 200,
  content_type => "text/html",
  content => "Hello World",
]);
```

```perl
my $res = SPVM::HTTP::Response->new_with(new_hash[
  status => 200,
]);
```

### FIELDS

#### status

```perl
$res->{status} = SPVM::HTTP::Status->OK;
```

```perl
$res->{status} = 200;
$status = $res->{status};
```

#### headers

```perl
$headers = $res->{headers};
$res->{headers} = new_hash([ 'Content-Type' => 'text/html' ]);
$res->{headers} = SPVM::HTTP::Headers->new;
```

#### content

```perl
$res->{content} = $content;
```

#### content_type, content_length, content_encoding

```perl
$res->{content_type} = "text/plain";
$res->{content_length} = 123;
$res->{content_encoding} = "gzip";
```

### METHODS

#### constructors

```perl
$res = SPVM::HTTP::Response->new;
$res = SPVM::HTTP::Response->new_with(new_hash([
  status => $status,
]));
$res = SPVM::HTTP::Response->new_with(new_hash([
  status  => $status,
  headers => $headers,
]));
$res = SPVM::HTTP::Response->new_with(new_hash([
  status  => $status,
  headers => $headers,
  content => $content,
]));
```

#### redirect

```perl
$res->redirect("http://www.example.com/"); # 302 Found
$res->redirect("http://www.example.com/", 303);
```

## SPVM::HTTP::Response::Builder

```perl
sub GET : SPVM::HTTP::Response::Builder::_GET ($url : string);
sub HEAD : SPVM::HTTP::Response::Builder::_HEAD ($url : string);
sub POST : SPVM::HTTP::Response::Builder::_POST ($url : string);
sub PUT : SPVM::HTTP::Response::Builder::_PUT ($url : string);
```

### SYNOPSIS

```perl
my $response = SPVM::HTTP::Response::Builder
  ->POST("http::/example.com")
  ->add_json($json)
  ->finalize();
```

## SPVM::HTTP::Cookies

- TODO
- 参考
  - [HTTP::Cookies - HTTP cookie jars - metacpan.org](https://metacpan.org/pod/HTTP::Cookies)
  - [RFC 6265 — HTTP State Management Mechanism （日本語訳）](https://triple-underscore.github.io/http-cookie-ja.html)


## SPVM::HTTP::URL

- TODO
- 参考
  - [URI-1.76 - Uniform Resource Identifiers (absolute and relative) - metacpan.org](https://metacpan.org/release/URI)
  - [URI::URL - Uniform Resource Locators - metacpan.org](https://metacpan.org/pod/URI::URL)

## SPVM::HTTP::URL::Escape

- TODO
- 参考
  - [URI::Escape - Percent-encode and percent-decode unsafe characters - metacpan.org](https://metacpan.org/pod/URI::Escape)

## SPVM::HTTP::URL::QueryParam

- TODO
- 参考
  - [URI::QueryParam - Additional query methods for URIs - metacpan.org](https://metacpan.org/pod/URI::QueryParam)


## SPVM::Time

- TODO

## SPVM::MIME::Base64

- TODO
