### ISSUE TITLE
Alpine Linux support

### ISSUE THREAD

**Issue by Cellesti** [yuki-kimoto/SPVM#486]
Hello, i am interested in packaging SPVM for Alpine Linux, and have tried to compile version 0.989082.

After removing the if check in `Makefile.PL` that `die`s when running on Alpine, SPVM compiles and tests seem to be passing.

I think maybe the segfault on Alpine problem has been solved. May i know what was the code/command that originally produced the segfault?

**Comment by yuki-kimoto** [comment]
> May i know what was the code/command that originally produced the segfault?

Sorry. It was a long time ago, so I don't remember which code caused the segmentation fault. Some SPVM test code running on CPAN tester caused a segmentation fault.

> After removing the if check in Makefile.PL that dies when running on Alpine, SPVM compiles and tests seem to be passing.

Thank you for compilation and tests.

I will remove the if check in Makefile.PL that dies when running on Alpine. Is it OK?

**Comment by yuki-kimoto** [comment]
Modules for File IO and socket IO is not stable.

I think that modules for algorithm and modules that are port of Perl moudles will be more stable.

For examples: MIME::Base64, Digest::MD5.

**Comment by yuki-kimoto** [comment]
I will remove the if check in Makefile.PL that dies when running on Alpine.

bfc5e6ddbac7a2046c8fd3a7586cf40e243e85c3

**Comment by yuki-kimoto** [comment]
SPVM 0.989086 that supports Alpine was released to CPAN.

**Comment by yuki-kimoto** [comment]
Thank you!
