### ISSUE TITLE
最低限必要なヘッダを作る

### ISSUE THREAD

**Issue by motxx** [yuki-kimoto/SPVM#56]
HTTP::Tiny->_prepare_headers_and_cb に該当する機能

**Comment by motxx** [comment]
Implemented at: #58

**Comment by yuki-kimoto** [comment]
ありがとう。これは、マージしてOK?

**Comment by motxx** [comment]
大丈夫だと思います。`_prepare_headers_and_cb` の一部の機能になります。

**Comment by yuki-kimoto** [comment]
マージしました
