### ISSUE TITLE
Implement write_request for GET

### ISSUE THREAD

**Issue by motxx** [yuki-kimoto/SPVM#59]
Implement simple `GET` request.
For testing easily, `SPVM::IO::File` used instead of `SPVM::IO::Socket` for now.

**Comment by motxx** [comment]
Implemented at: #60

**Comment by yuki-kimoto** [comment]
moti君のほうで、試験できるHTTPページはありますか?

実際に、IO::Socketで書き込んで、レスポンスの文字列を取得するところまで進んでみませんか?

**Comment by yuki-kimoto** [comment]
selectによるタイムアウトの実装は、補助的なものなので、あとで追加するという方向で、ソケットに書き込んで、受け取るというところの実装をまずやってみませんか。

**Comment by yuki-kimoto** [comment]
ひとつ、認識違いがないかの確認です。

最終的に「SPVM/HTTP/Client.spvm」という一つだけのモジュールを作成するということに、認識の相違はありませんか?

**Comment by motxx** [comment]
> moti君のほうで、試験できるHTTPページはありますか?
>
> 実際に、IO::Socketで書き込んで、レスポンスの文字列を取得するところまで進んでみませんか?

すみません、これについて別途質問させてください...

> selectによるタイムアウトの実装は、補助的なものなので、あとで追加するという方向で、ソケットに書き込んで、受け取るというところの実装をまずやってみませんか。

はい、承知しました。

**Comment by motxx** [comment]
> 最終的に「SPVM/HTTP/Client.spvm」という一つだけのモジュールを作成するということに、認識の相違はありませんか?

以下のファイルについて

```
lib/SPVM/HTTP/Client.spvm
lib/SPVM/HTTP/Client/CookieJar.spvm
lib/SPVM/HTTP/Client/CookieJar/Cookie.spvm
lib/SPVM/HTTP/Client/CookieJar/CookieParser.spvm
lib/SPVM/HTTP/Client/Handle.spvm
lib/SPVM/HTTP/Client/Handle/SocketWrapper.spvm
lib/SPVM/HTTP/Client/Request.spvm
lib/SPVM/HTTP/Client/Response.spvm
```

- `HTTP::Tiny` は `HTTP::CookieJar` に依存しているため `SPVM::HTTP::Client::CookieJar` が存在します(サーバ側想定の機能はないため Client 以下に置きました)。
- `Cookie.spvm`, `CookieParser.spvm` は `HTTP::CookieJar` ではハッシュで実装されています。
- `HTTP::Tiny` が `HTTP::Tiny::Handle` を同一モジュール内に含んでいるため、現状 `SPVM/HTTP/Client/Handle.spvm` が存在します。
- `SocketWrapper.spvm` はとりあえず実装なのでいりません......削除予定です。
- `Client/Request.spvm`, `Client/Response.spvm` は `HTTP::Tiny` ではハッシュで実装されています。

**Comment by yuki-kimoto** [comment]
HTTP::Client::Handleは、公開しないので、HTTP::Clientの中に入れる(パッケージは、複数宣言できます)

HTTP::Client::Responseは、HTTP::Tinyにはなけれど、必要そう
(ハッシュで返すと非常にユーザーが使いにくいので)

HTTP::Requestは、消す方向で可能ですか?

lib/SPVM/HTTP/Client/CookieJar.spvm
lib/SPVM/HTTP/Client/CookieJar/Cookie.spvm
lib/SPVM/HTTP/Client/CookieJar/CookieParser.spvm

これはHTTP::Client::CookieJarにまとめることは可能ですか?

残りの以下ですが、最終的に、HTTP::Tiny内のサブルーチンにすることは可能ですか?

HTTP::URL
HTTP::Headers
HTTP::URL::Parameters
HTTP::URL::Escape
HTTP::URL::Encode

**Comment by yuki-kimoto** [comment]
SPVM/HTTP/Client.spvm
SPVM/HTTP/Client/CookieJar.spvm
SPVM/HTTP/Client/Response.spvm

ここまで、減らす方向性で考えています。

**Comment by motxx** [comment]
> HTTP::Client::Handleは、公開しないので、HTTP::Clientの中に入れる(パッケージは、複数宣言できます)
> HTTP::Client::Responseは、HTTP::Tinyにはなけれど、必要そう
> HTTP::Requestは、消す方向で可能ですか?
> これはHTTP::Client::CookieJarにまとめることは可能ですか?

こちら、大丈夫です。承知しました。

> 残りの以下ですが、最終的に、SPVM::HTTP::Client内のサブルーチンにすることは可能ですか?
> ...
> ここまで、減らす方向性で考えています。

`SPVM::HTTP::URL` 等、やはり冗長なモジュールという感じが強いので
全て Client, CookieJar, Response 内にまとめてしまうのが良いと思います :bow:

**Comment by yuki-kimoto** [comment]
> moti君のほうで、試験できるHTTPページはありますか?

> 実際に、IO::Socketで書き込んで、レスポンスの文字列を取得するところまで進んでみませんか?

> すみません、これについて別途こちらから質問いたします 🙇

あらためてこちらに戻りますね。

**Comment by motxx** [comment]
> すみません、これについて別途こちらから質問いたします 🙇

こちら自分に勘違いがあり、取り敢えず自己解決出来そうです 💦

**Comment by motxx** [comment]
標題の実装が済んでいるのでクローズします
