### ISSUE TITLE
SPVM::MIME::DecoderとSPVM::MIME::Encoderの削除

### ISSUE THREAD

**Issue by yuki-kimoto** [yuki-kimoto/SPVM#63]
SPVM::MIME::DecoderとSPVM::MIME::Encoderですが、

こちら消しても大丈夫でしょうか?

**Comment by motxx** [comment]
すみません、こちら完全に不要ですね......
#64 に PR を作りました

**Comment by yuki-kimoto** [comment]
ありがとう

マージしました。
