### ISSUE TITLE
sprintfの実装

### ISSUE THREAD

**Issue by yuki-kimoto** [yuki-kimoto/SPVM#72]
sprintfの実装がHTTP::Clientの日付を出力するために必要ということで忘れないようにメモ

**Comment by motxx** [comment]
実装内容
1. フォーマットの読取で `$pat = [[specifier_begin, specifier_end, specifier_type], ...]` を作成 (不明な specifier の場合 `warn` + skip)
2. 次の順に `$output: string` に代入: `sliceb($format, 0, $pat[0][0])`, `$args[0]`,`sliceb($format, $pat[0][1], $pat[2][0])`, `$args[1]`, ... 
3. `$args` の要素が不足の場合: `warn` + `specifier` のデフォルト値で置換 (`%s` なら `""`, `%d` なら `0`, ...)
要素が過剰の場合: `warn`

**Comment by yuki-kimoto** [comment]
いくつか質問があります

1.メソッドの引数と戻り値は、どうなりますか?
2. 最初に実装するフォーマット指定子「%d」「%f」など
3. 入力のサンプル、出力のサンプルをいくつか

ユーザーから見た「入り口」と「出口」は、どうなるでしょうか?

**Comment by yuki-kimoto** [comment]
pull requestありがとう。

追加のレビューを書きます。

**Comment by yuki-kimoto** [comment]
<b>書式指定子でない文字列</b>

書式指定子でない文字列の場合ですが、これは、まとめてString::Bufferに追加するのがよいと思います。

https://github.com/yuki-kimoto/SPVM/blob/sprintf/lib/SPVM/Util.spvm#L158

理由: 1文字づつ追加するよりも、パフォーマンスが良いため。

%が来るまでの位置をまとめて、pushする感じですね。

**Comment by yuki-kimoto** [comment]
<b>プライベートなパッケージ変数</b>

roを指定すると、パブリックなメソッドができてしまいますので、これはなしですね。

デフォルトでprivateなので、指定子は、なくても大丈夫です。

https://github.com/yuki-kimoto/SPVM/blob/master/lib/SPVM/Util.spvm#L118

**Comment by motxx** [comment]
ありがとうございます。#142 まで反映させました。
以下、未反映部分についてです。

> 文字列の先頭から終わりまでのループ
> 文字が%ではない場合
> %dと%ldのフォーマットは、10で割る方法で

一旦可読性の問題がある気がしたので、該当部分を書き直してみました。
`%%` のエスケープはそもそもバグがあったため、修正しました。

**Comment by yuki-kimoto** [comment]
ネイティブ実装のやり方、moti君マスターしちゃってますね。

**Comment by yuki-kimoto** [comment]
https://github.com/yuki-kimoto/SPVM/pull/142

こちらマージしたのですが、試験が落ちましたので、リバートしております。

もしかしたら、こちらの環境だけで落ちているかもしれないので

いったんmasterをマージしてもらえますか。

**Comment by yuki-kimoto** [comment]
<b>引数の変数名</b>

これは、引数の個数という名前にできそうですね。

```
$specifier_count
```

https://github.com/yuki-kimoto/SPVM/blob/05075d40d334252197997b380fdb193c7a57b288/lib/SPVM/Util.spvm#L164

**Comment by yuki-kimoto** [comment]
追加のレビューです。

<b>引数が多かった場合の仕様変更</b>

引数が多かった場合に、例外を投げるということになっていますが、単に無視するという仕様に変更します。

**Comment by yuki-kimoto** [comment]
こちら完了しましたので、クローズします。
