### ISSUE TITLE
http client header-lines, content の read

### ISSUE THREAD

**Issue by motxx** [yuki-kimoto/SPVM#74]

**Comment by motxx** [comment]
こちらで最低限の実装をしました。
https://github.com/yuki-kimoto/SPVM/pull/77

`t/default/lib-SPVM-HTTP-Client.t` でレスポンスヘッダを読み、content は中身を確認できるようにファイルに吐き出させています。

**Comment by yuki-kimoto** [comment]
ありがとう。良い感じです。

これでGETリクエストができるようになりましたね。

GETが終わったので次は、優先度が高いところの実装は、以下ですね。

HEAD
POST

HEADはGETを簡単にしたものなので、いけそう。

POSTを実装するとしたら、どの部分の実装が、ユーザーの最初の入力する位置から近いですかね?

**Comment by yuki-kimoto** [comment]
あと

SPVM.xsc

というのが、入ってきたんだけど、これはなんだろうか?

**Comment by motxx** [comment]
> SPVM.xsc

すみません、エディタ上で気づかないうちに操作ミスしていたようです。
#78 で削除する PR を出しました :bow:

**Comment by motxx** [comment]
> HEADはGETを簡単にしたものなので、いけそう。
#82 で実装します。

> POSTを実装するとしたら、ユーザーの入力インターフェースはどんな感じになりますかね?
#81 で検討します。
