### ISSUE TITLE
array/hash fields?

### ISSUE THREAD

**Issue by rurban** [yuki-kimoto/SPVM#8]
your fields can only hold scalar's, whilst cperl and perl6 can do `has @array;` or `has %hash;`.
e.g.

    class XX { has %h; }; my $o = XX->new; $o->h = (has => 'field'); $o->h{has}
    class XY { has @a; }; my $a = XY->new; $a->a = (0..2); $a->a[0]

names may not collide with scalar fields. the ctor just needs to be extended a bit for those.
getters and setters are trivial, just return the field entry.
types are like with normal my array and hash decls.

only complicated is the parser to detect those types, and allow the `[{`. In cperl I named the op `oelem`.

**Comment by yuki-kimoto** [comment]
@rurban 

I have questions.

Perl have already array reference and hash reference. This is why scalar variable(or field) can hold array and hash by using reference. 

What benefit have `has %h;` and `has @a;` syntax? 

If what can do is same, I want to choice minimal syntax.

by the way,
I red many your blog posts. It is interesting to know Perl problems.

**Comment by rurban** [comment]
The biggest benefit is the ability to type fields:

`has int @a[2];` declares a native array of 2 int slots.
`has str %h` only allows string hash values.

With `has a :Reg(Array(int));` it starts getting ugly.

With native arrays you can immediately write to array slots without refcount updates. 
~2x faster and 4x less memory.

**Comment by yuki-kimoto** [comment]
OK, You find value in syntax sugar and static count array.

SPVM has the following syntax. All array size is decided at run-time as same as Java.

    has nums : int[];
    
    my $nums : nums[] = malloc int[2];
