### ISSUE TITLE
HTTP Client POST のインターフェース

### ISSUE THREAD

**Issue by motxx** [yuki-kimoto/SPVM#81]
> POSTを実装するとしたら、ユーザーの入力インターフェースはどんな感じになりますかね?

form の送信は以下でしょうか。
```perl
sub post_form ($self : self, $url : string, $data : SPVM::Hash);
```

JSON は一先ず content に貼り付けて送信することを考えています。
```perl
$client->request("POST", $url, hash([(object)
  headers => hash([(object)
    "Content-Type" => "application/json",
  ]),
  content => SPVM::JSON->new->encode($data),
]));
```

**Comment by yuki-kimoto** [comment]
該当するのはここですね。

```
sub post_form {
    return $self->request('POST', $url, {
            %$args,
            content => $self->www_form_urlencode($data),
            headers => {
                %$headers,
                'content-type' => 'application/x-www-form-urlencoded'
            },
        }
}
```

これを元にして考えてみませんか。一般的なフォームのPOSTから。

それと、ユーザーの入力は、ハッシュではなくって、単なるオブジェクトの配列にしてみませんか?

```
$client->request("POST", $url, [(object)
  headers => [(object)
    "Content-Type" => "application/json",
  ],
  content => SPVM::JSON->new->encode($data),
]));
```

ユーザー側の負担を減らして、受け取った側で、ハッシュに変換みたいな感じです。

**Comment by yuki-kimoto** [comment]
補足しておくと、POSTの入力データは、繰り返しが存在するので、ハッシュで受け取ると、同じキーが削除されてしまうというのがあるので、配列で受け取ることは必須になります。

<form>
  <input type="checkbox" name="foo" value="1">
  <input type="checkbox" name="foo" value="2">
</form>

**Comment by motxx** [comment]
ご教授いただきありがとうございます。配列で受け取らないと削除されるのを読み落としていました 💦 

> それと、ユーザーの入力は、ハッシュではなくって、単なるオブジェクトの配列にしてみませんか?
ユーザー側の負担を減らして、受け取った側で、ハッシュに変換みたいな感じです。

今後、他の実装でもこの方式を採用して良いでしょうか。

**Comment by yuki-kimoto** [comment]
> 今後、他の実装でもこの方式を採用して良いでしょうか。以下のような形式が perl に近いかなと思います。

はい、お願いします。

**Comment by yuki-kimoto** [comment]
こちらクローズします。
