### ISSUE TITLE
HTTP Client HEAD の実装

### ISSUE THREAD

**Issue by motxx** [yuki-kimoto/SPVM#82]
現状の実装でほぼ完結していますが一部バグ修正が必要です。

```perl
# L360
    if (my $got = $self->{rbuf}->length) {
```
```
Invocant must be defined
  from SPVM::HTTP::Client::Handle->_read at SPVM/HTTP/Client.spvm line 380
  from SPVM::HTTP::Client::Handle->_read_content_body at SPVM/HTTP/Client.spvm line 468
```

**Comment by yuki-kimoto** [comment]
バグの内容を教えてもらえますか?

**Comment by motxx** [comment]
`GET` 実装時に以下の問題があったため修正しました。
- リクエストラインの不正
- `rbuf` を初期化する際、誤って `undef` で解放していた (標題の修正)

`HEAD` のリクエストで `200 OK` が返されてテストが正常終了することを確認しました。
HTTPレスポンスヘッダの値に 'Accept-Encoding' が入るケースですが、[Vary HTTPレスポンスヘッダ](https://developer.mozilla.org/ja/docs/Web/HTTP/Headers/Vary)だったため、問題ありませんでした。

**Comment by motxx** [comment]
実装: #89

**Comment by yuki-kimoto** [comment]
HEADが通りましたね!

ありがとう。
