### ISSUE TITLE
SPVM::COREのhash関数の削除とSPVM::Hashのデフォルトの読み込みの解除

### ISSUE THREAD

**Issue by yuki-kimoto** [yuki-kimoto/SPVM#83]
SPVM::COREのhash関数の削除とSPVM::Hashのデフォルトの読み込みの解除。

理由: SPVM::COREがSPVM::Hashに依存しているのが、将来、分離を考えたときに、良くない影響をもたらすような予感がしてきました。

**Comment by motxx** [comment]
SPVM::Hash は高頻度で使われますが native で実装する必要はあるでしょうか？

**Comment by yuki-kimoto** [comment]
ハッシュが、高速であることが求められるまで、保留にしましょう。

nativeの前に、precompileで、十分速度がでれば、それでよいという感じもします。

**Comment by yuki-kimoto** [comment]
SPVM::Hashの読み込みを解除しました
