### ISSUE TITLE
http client で request の content を write

### ISSUE THREAD

**Issue by motxx** [yuki-kimoto/SPVM#99]

**Comment by yuki-kimoto** [comment]
あれ、writeの前に、POSTのデータから、URLエンコードして、ボディを作るところまでの部分のissueは、これでしょうか?

**Comment by motxx** [comment]
#98
こちらの issue で実施します。タイトルを URL::Encode の移動から変更しました。

**Comment by motxx** [comment]
実装したためクローズします :bow:
